apiVersion: v1
kind: Secret
metadata:
  name: postgresqlPassword
  labels:
    app: example-voting-app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresPassword: {{ .Values.secret_{{ .Release.Namespace }}_postgresql_postgresPassword | b64enc | quote }}